# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqXEPLxmqgcB_nDr5iixDr-cY8NNt5EK
"""

!pip install xlsxwriter

import xlsxwriter

book = xlsxwriter.Workbook("Sales.xlsx")

prod_name ="v_neck T-shirt"
prod_code ="v_tee"
sku_code ="T001neck"

s = book.add_worksheet("sales")

import pandas as pd
df = pd.read_csv("/content/sample_data/mnist_train_small.csv")

s.write(1,0,"Product Name")
s.write(1,1,prod_name)
s.write(2,0,"Product Code")
s.write(2,1,prod_code)
s.write(3,0,"Sku code")
s.write(3,1,sku_code)

book.close()

ls

df = pd.read_excel("Sales.xlsx")

df

