# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17n466rzysmomdp6x_pZP6o9vrLAy8SwJ
"""

import xlsxwriter

import pandas as pd
import xlsxwriter

df = pd.read_csv("/content/sample_data/california_housing_test.csv")

from xlsxwriter.utility import xl_rowcol_to_cell

df.head()

x=df.groupby(["total_bedrooms","population","total_rooms"])["housing_median_age"].count()

x=x.reset_index()

x

pip install xlsxwriter

writer=pd.ExcelWriter('enchaned.xlsx',engine='xlsxwriter')

df.to_excel(writer,index=False,sheet_name="report")

ls

workbook = writer.book
worksheet = writer.sheets['report']

worksheet.set_zoom(90)

# Set header formating
header_format = workbook.add_format({
    "valign":"vcenter",
    "align":"center",
    "bg_color":"#951F06",
    "bold":True,
    "font_color":"#FFFFFF"
})

# ADD Title
title ="Montly Sales Report"

#merge cells
format = workbook.add_format()
format.set_font_size(20)
format.set_font_color("#333333")

# Sub Header
subheader = "Sales report for classic Vest M"
worksheet.merge_range('A1:AS1',title,format)
worksheet.merge_range('A2:AS2',subheader)
worksheet.set_row(2,len(df.columns))

#puting it all together
#write columns header with define format
for col_num,value in enumerate(x.columns.values):
  worksheet.write(2,col_num,value,header_format)

for col_num,value in enumerate(x.columns.values):
  print(col_num,value)

money_fmt = workbook.add_format({'num_format':'$#,##0.00'})

total_fmt=workbook.add_format({'align':'right','num_format':'$#,##0','bold':True,'bottom':6})

# #Adjust column with
worksheet.set_column('F:I',12,money_fmt)

number_rows = len(df.index)

#Add total rows
for column in range(5,9):
  #Determine where we place formula
  cell_location=xl_rowcol_to_cell(number_rows+1,column)
  #Get range to use the sum formula
  start_range=xl_rowcol_to_cell(3,column)
  print(start_range)
  end_range = xl_rowcol_to_cell(number_rows,column)
  print(end_range)
  #Construct and write formula
  formula="=SUM({:s}:{:s})".format(start_range,end_range)
  print(formula)
  worksheet.write_formula(cell_location,formula,total_fmt)

worksheet.write_string(number_rows+1,4,"Total",total_fmt)

writer.save()

ls

